name: Auto Build

on:
  push:
    branches: [ master, develop, main ]
  pull_request:
    branches: [ master, develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Synopsys Action
      uses: synopsys-sig/synopsys-action@v1.2.0
      with:
        coverity_url: ${{ secrets.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        coverity_project_name: "ZKEACMS"
        coverity_stream_name: "ZKEACMS"
    
